#nullable enable

namespace Ariadne.Menus;

internal static class CharacterAppearanceDescriptions
{
	private static readonly string[] VanillaHairstyles =
	[
		/* 1 */ "Large shaggy hair with uneven layers and flared sides.",
		/* 2 */ "Short rounded messy hair with thick side-swept bangs.",
		/* 3 */ "Smooth side-swept hair with a long pointed beard reaching the chest.",
		/* 4 */ "Very wide, flat-topped hair projecting sharply to both sides.",
		/* 5 */ "Rounded bob with thick bangs covering much of the face.",
		/* 6 */ "Shoulder-length hair with heavy bangs and a small rear ponytail.",
		/* 7 */ "Rounded curly hair with a long thick braid down the back.",
		/* 8 */ "Short smooth crop with a thick straight fringe.",
		/* 9 */ "Large side-swept curls projecting forward across the forehead.",
		/* 10 */ "Thick bangs with a short high ponytail bent behind the head.",
		/* 11 */ "Enormous rounded hair sweeping broadly behind the head.",
		/* 12 */ "Short side-swept hair gathered into a small rounded bun.",
		/* 13 */ "Medium curly hair with thick locks framing the face.",
		/* 14 */ "Medium messy hair with several uneven outward-pointing tufts.",
		/* 15 */ "Smooth combed-back hair with two pointed tufts standing upward.",
		/* 16 */ "Completely bald.",
		/* 17 */ "Large round afro surrounding the head.",
		/* 18 */ "Smooth combed hair with a small pointed beard below the chin.",
		/* 19 */ "Thick bangs with a large curled ponytail behind the head.",
		/* 20 */ "Short smooth hair with a center part and swept sides.",
		/* 21 */ "Tall pointed hair split down the middle, with two rear spikes.",
		/* 22 */ "Heavy bangs with a single small curled ponytail.",
		/* 23 */ "Wavy bowl-like hair with a long ponytail down the back.",
		/* 24 */ "Wild upright hair with many long, sharply pointed spikes.",
		/* 25 */ "Smooth center-parted hair with two broad side-swept sections.",
		/* 26 */ "Smooth hair gathered into large rounded buns over both ears.",
		/* 27 */ "Thick bangs with a neatly combed short ponytail.",
		/* 28 */ "Medium straight hair pushed upward in front and hanging behind.",
		/* 29 */ "Short combed hair with a tall, swept-up front.",
		/* 30 */ "Rounded bowl cut with a long straight high ponytail.",
		/* 31 */ "Short windswept hair brushed strongly backward.",
		/* 32 */ "Short tousled hair with two sharp upward crown tufts.",
		/* 33 */ "Two short rounded pigtails with thick bangs.",
		/* 34 */ "Shoulder-length hair divided into two small braids.",
		/* 35 */ "Very short tightly braided hair forming a compact cap.",
		/* 36 */ "Short hair with several narrow spikes standing upright.",
		/* 37 */ "Broad mop-like hair with a rounded, umbrella-shaped outline.",
		/* 38 */ "Tall smooth pompadour swept upward and backward.",
		/* 39 */ "Large high ponytail with a thick wavy tail.",
		/* 40 */ "Short straight hair with heavy bangs covering one side of the face.",
		/* 41 */ "Medium center-parted hair with a single large curled lock.",
		/* 42 */ "Center-parted hair with a curled fringe partly covering one eye.",
		/* 43 */ "Smooth center-parted bob with one broad side-swept section.",
		/* 44 */ "Flame-shaped spikes rising high and sweeping behind the head.",
		/* 45 */ "Rounded bob with a diagonal part and one curled side.",
		/* 46 */ "Short asymmetrical bob with a strongly diagonal part and swept fringe.",
		/* 47 */ "Thick curly hair gathered into a medium rear ponytail.",
		/* 48 */ "Straight medium-length hair in a high ponytail with full bangs.",
		/* 49 */ "Smooth hair gathered into a large braided bun high at the back.",
		/* 50 */ "Very close-cropped buzz cut.",
		/* 51 */ "Medium curly ponytail with thick side-swept bangs.",
		/* 52 */ "Straight swept hair with a pointed fringe and split rear sections.",
		/* 53 */ "Dramatic forward-swept quiff over a cropped side and visible eyebrow.",
		/* 54 */ "Short, very puffy and messy hair with several pointed tufts.",
		/* 55 */ "Short-to-medium hair with layered, leaf-shaped bangs and a front part.",
		/* 56 */ "Very long wavy hair with loose pointed sections down the back.",
		/* 57 */ "Long straight hair paired with a long full beard.",
		/* 58 */ "Straight center-parted hair with a thick medium-length beard.",
		/* 59 */ "Short center-parted hair with a broad medium-length beard.",
		/* 60 */ "Very short side-parted hair with a large fluffy beard.",
		/* 61 */ "Center-parted hair with curved bangs and a short narrow beard.",
		/* 62 */ "Short front-parted hair with one side lock and a small beard.",
		/* 63 */ "Neatly combed center-parted hair with a mustache and full beard.",
		/* 64 */ "Long center-parted hair with a mustache and very long beard.",
		/* 65 */ "Very long straight hair with Y-shaped bangs and pointed side locks.",
		/* 66 */ "Long straight hair with a narrow braid tucked along the front.",
		/* 67 */ "Long center-parted hair twisted at the back with curved side locks.",
		/* 68 */ "Medium straight hair with a simple front part.",
		/* 69 */ "Long straight hair with a diagonal part and prominent bangs.",
		/* 70 */ "Long wavy hair swept over one eye with a straight back length.",
		/* 71 */ "Medium hair with a widow's peak and exposed ears.",
		/* 72 */ "Medium straight hair with leaf-shaped bangs and a center part.",
		/* 73 */ "Long straight hair with strong center-parted bangs covering one eye.",
		/* 74 */ "Center-parted hair with leaf-shaped bangs and a thick long braid.",
		/* 75 */ "Short neat hair with a very thin curled mustache.",
		/* 76 */ "Short center-parted hair with a broad fluffy mustache.",
		/* 77 */ "Bald head with one eyebrow, a tiny beard, and a long thin ponytail.",
		/* 78 */ "Short center-parted hair with a straight mustache curled upward at the ends.",
		/* 79 */ "Front-parted hair with bangs and a short mid-height ponytail.",
		/* 80 */ "Thick bangs with a short fluffy ponytail behind the head.",
		/* 81 */ "Very long straight ponytail divided into several thick sections.",
		/* 82 */ "Two extremely long wavy ponytails beneath a center-parted fringe.",
		/* 83 */ "Short straight hair split into two sections with full bangs.",
		/* 84 */ "Puffy shoulder-length hair with thick, strongly defined bangs.",
		/* 85 */ "Large ponytail with thick bangs and two pointed, ear-like crown tufts.",
		/* 86 */ "Long segmented braid with bangs covering one eye.",
		/* 87 */ "Very large curly ponytail with a Y-shaped center part and side bangs.",
		/* 88 */ "Very long wavy hair draped over one eye and down the back.",
		/* 89 */ "Short curly side-swept hair.",
		/* 90 */ "Curly-ended bob with pronounced bangs covering one eye.",
		/* 91 */ "Straight medium ponytail set high behind thick bangs.",
		/* 92 */ "Medium wavy low ponytail with long straight bangs.",
		/* 93 */ "Short front hair with one enormous pointed spike rising behind.",
		/* 94 */ "Short rounded straight hair split into two smooth sections.",
		/* 95 */ "Mostly bald head with a long rear ponytail and small mustache.",
		/* 96 */ "Medium straight, slightly uncombed hair with a strong center part.",
		/* 97 */ "Mostly bald, leaving a small patch at the front and sides.",
		/* 98 */ "Rounded bowl-like hair topped by a raised bun.",
		/* 99 */ "Medium coiled hair forming a broad triangular silhouette.",
		/* 100 */ "Medium coiled hair forming a squarer, more even silhouette.",
		/* 101 */ "Square-shaped coils with two thin front locks and a small beard.",
		/* 102 */ "Long fluffy curls with thick back length.",
		/* 103 */ "Medium curly hair with a full fringe.",
		/* 104 */ "Long curly hair with layered, leaf-shaped bangs.",
		/* 105 */ "Short front-parted hair swept over one eye.",
		/* 106 */ "Short rounded bowl cut with a front part.",
		/* 107 */ "Long wavy hair with full bangs and one tall loose cowlick.",
		/* 108 */ "Smooth rounded hair with a small mustache.",
		/* 109 */ "Bald except for one thin upright cowlick.",
		/* 110 */ "Tightly pulled-back hair with a short mid-height ponytail and visible eyebrow.",
		/* 111 */ "Short curled bob with one tall upright cowlick.",
		/* 112 */ "Short side-swept hair with thick, sharply defined bangs.",
		/* 113 */ "Long side-swept hair falling past the shoulder.",
		/* 114 */ "Neatly combed hair with one large curled front lock.",
		/* 115 */ "Short flat hair with pronounced bangs split into two sections.",
		/* 116 */ "Very short bangs with one closely shaved side.",
		/* 117 */ "Very short side-shaved hair with dark beard stubble.",
		/* 118 */ "Short combed hair with a shaved side, small beard, and mustache.",
		/* 119 */ "Short rounded hair with a long thin curled mustache.",
		/* 120 */ "Short tousled hair with a small beard and mustache.",
		/* 121 */ "Very short thin hair with a long narrow beard.",
		/* 122 */ "Smooth rounded combed hair with a small mustache.",
		/* 123 */ "Rounded combed hair with a shaved side and thick mutton chops.",
		/* 124 */ "Huge wavy rock-star hair with thick bangs and a high swept-back tail.",
		/* 125 */ "Large rounded mushroom-shaped hair formed by tightly clustered curls.",
		/* 126 */ "Tall curled pompadour shaped like a hooked wave.",
		/* 127 */ "Wide saucer-shaped hair with a raised center and pointed horizontal edges.",
		/* 128 */ "Dense wild spikes radiating around the entire head.",
		/* 129 */ "Enormous windswept spikes extending far to one side.",
		/* 130 */ "Large rounded spiky afro with a rough outline.",
		/* 131 */ "Short forward-swept bob with a thick curved fringe.",
		/* 132 */ "Wild swept-back hair with several large pointed spikes.",
		/* 133 */ "Enormous long windswept hair spreading in sharp locks to both sides.",
		/* 134 */ "Very long voluminous hair with a high crown and thick side lengths.",
		/* 135 */ "Long hair with heavy side bangs and shoulder-length locks.",
		/* 136 */ "Neat short rounded cut with a smooth side part.",
		/* 137 */ "Short flat-topped hair with a narrow pointed beard.",
		/* 138 */ "Broad short quiff swept strongly to one side.",
		/* 139 */ "Long flat fringe swept horizontally over a close undercut.",
		/* 140 */ "Bald head with a wide handlebar mustache.",
		/* 141 */ "Simple short bowl cut with a gently curved fringe.",
		/* 142 */ "Round compact afro made of large curls.",
		/* 143 */ "Full shoulder-length pageboy cut with rounded ends.",
		/* 144 */ "Tall retro pompadour swept upward at the front.",
		/* 145 */ "Very short crew cut forming a close cap.",
		/* 146 */ "Two small high side buns with a short center fringe.",
		/* 147 */ "Long high side ponytail with a thick wavy tail.",
		/* 148 */ "Close-cropped hair with a small rounded goatee.",
		/* 149 */ "Short hair with one upright horn-like tuft and a small goatee.",
		/* 150 */ "Short spiky crest paired with a small pointed goatee.",
		/* 151 */ "Short side-parted hair with a neatly pointed goatee.",
		/* 152 */ "Short brushed-back hair with a long narrow goatee.",
		/* 153 */ "Bald head with a broad full beard.",
		/* 154 */ "Very short slicked hair with a small pointed goatee.",
		/* 155 */ "Short swept hair with a very long tapered beard.",
		/* 156 */ "Tousled short hair with a broad full beard.",
		/* 157 */ "Short upright center tuft with hair wrapping one cheek and a small beard.",
		/* 158 */ "Shaggy medium hair with a long thick beard.",
		/* 159 */ "Tall pointed topknot with a long narrow tapered beard.",
		/* 160 */ "Wild side-swept spikes with a broad hanging beard.",
		/* 161 */ "Bald head with a large curled handlebar mustache.",
		/* 162 */ "Short rounded crop with a small pointed chin tuft.",
		/* 163 */ "Long thick side ponytail hanging well below the shoulder.",
		/* 164 */ "Enormous squared-off flattop rising high and extending far sideways.",
		/* 165 */ "Elaborate very long ponytail curling upward like a scorpion tail.",
	];

	private static readonly string[] ClothingStyles =
	[
		"Male starter style: a sleeveless tunic over a long-sleeved undershirt, with long pants and large shoes.",
		"Male sticker style: a skull T-shirt with baggy pants and large shoes.",
		"Male gangster style: a sleeveless shirt and bracelet, with long pants and boots.",
		"Male coat style: a trench coat with long pants and large shoes.",
		"Female starter style: a short-sleeved crop top over a long-sleeved undershirt, with short shorts and small shoes.",
		"Female sticker style: a heart T-shirt with baggy pants and large shoes.",
		"Female gangster style: a sleeveless shirt and bracelet, with long pants and boots.",
		"Female coat style: a trench coat with one rolled-up sleeve, long pants, and large shoes.",
		"Male dress style: a long robe over a short-legged garment, with sandals.",
		"Female dress style: a long dress with small shoes and a bracelet.",
	];

	internal static string? GetHairstyle(int hairId) =>
		hairId >= 0 && hairId < VanillaHairstyles.Length
			? VanillaHairstyles[hairId]
			: null;

	internal static string GetClothingStyle(int skinVariant) =>
		skinVariant >= 0 && skinVariant < ClothingStyles.Length
			? ClothingStyles[skinVariant]
			: $"Unknown clothing style {skinVariant + 1}.";
}
